export const siteIconNames = [
  'activity',
  'archive',
  'arrow-down',
  'arrow-right',
  'arrow-up-right',
  'article',
  'book-open',
  'box',
  'clock',
  'cloud',
  'compass',
  'code',
  'database',
  'external-link',
  'feather',
  'folder',
  'gamepad',
  'github',
  'heart',
  'home',
  'layers',
  'link',
  'mail',
  'map-pin',
  'menu',
  'message-circle',
  'monitor',
  'moon',
  'palette',
  'paw-print',
  'rocket',
  'rss',
  'search',
  'server',
  'sparkles',
  'sun',
  'terminal',
  'user',
  'users',
  'video',
  'x',
  'zap',
] as const

export type SiteIcon = (typeof siteIconNames)[number]

export const isSiteIcon = (value: string): value is SiteIcon =>
  (siteIconNames as readonly string[]).includes(value)
