import avatar from '@/assets/images/neko-cute.webp'
import articleSky from '@/assets/images/articles/anime-sky-city.webp'
import friendsBackground from '@/assets/images/friends-bg.webp'
import homeBackground from '@/assets/images/home-bg.webp'
import type { SiteConfig } from './schema'

/** 复制本文件为 site.ts 后填写资料；site.ts 不会被 Git 提交。 */
export const siteConfig: SiteConfig = {
  meta: {
    name: '你的名字',
    title: '你的名字 · 个人主页',
    description: '一个可配置的二次元个人主页。',
    keywords: '个人主页,开发者',
    siteUrl: 'https://example.com/',
    ogImage: '/og-card.webp',
  },
  appearance: {
    accent: '#a9b8ff',
    glassOpacity: 0.46,
    lightGlassOpacity: 0.86,
    globalBackground: {
      image: homeBackground,
      position: 'center center',
      overlay: 0.24,
      blur: 1,
      imageOpacity: 1,
      grayscale: 0,
      saturation: 1,
      brightness: 0.9,
      tintColor: '#101735',
      tintOpacity: 0.12,
      effect: 'stars',
      twinkles: true,
      autoPan: true,
    },
    lightBackground: {
      overlay: 0.05,
      blur: 2,
      imageOpacity: 0.92,
      grayscale: 0.04,
      saturation: 0.9,
      brightness: 1.05,
      tintColor: '#f6f2ff',
      tintOpacity: 0.3,
      effect: 'none',
      autoPan: false,
    },
    homeBackground: {
      overlay: 0.2,
      brightness: 0.98,
      saturation: 1.04,
      tintOpacity: 0.08,
    },
    friendsBackground: {
      image: friendsBackground,
      position: 'center center',
      overlay: 0.22,
      blur: 1,
      brightness: 0.94,
      saturation: 0.96,
      tintColor: '#25365d',
      tintOpacity: 0.1,
      effect: 'petals',
      autoPan: true,
    },
    contentBackground: {
      overlay: 0.34,
      blur: 4,
      imageOpacity: 0.92,
      grayscale: 0.12,
      saturation: 0.82,
      brightness: 0.72,
      tintColor: '#0d1430',
      tintOpacity: 0.22,
      effect: 'stars',
      autoPan: false,
    },
    readingBackground: {
      overlay: 0.5,
      blur: 6,
      imageOpacity: 0.72,
      grayscale: 0.18,
      saturation: 0.68,
      brightness: 0.58,
      tintOpacity: 0.34,
      effect: 'none',
      twinkles: false,
      autoPan: false,
    },
    lightReadingBackground: {
      overlay: 0.02,
      blur: 6,
      imageOpacity: 0.36,
      grayscale: 0.24,
      saturation: 0.48,
      brightness: 1.12,
      tintColor: '#f8f7ff',
      tintOpacity: 0.78,
      effect: 'none',
      twinkles: false,
      autoPan: false,
    },
    themeToggle: true,
  },
  navigation: [
    { label: '首页', to: '/', icon: 'home', enabled: true },
    { label: '文章', to: '/articles', icon: 'book-open', enabled: true },
    { label: '导航', to: '/navigation', icon: 'compass', enabled: true },
    { label: '友链', to: '/friends', icon: 'users', enabled: true },
    {
      label: '联系',
      icon: 'message-circle',
      enabled: true,
      children: [
        {
          id: 'bilibili',
          label: 'Bilibili',
          href: 'https://www.bilibili.com/',
          icon: 'bilibili',
          iconProvider: 'fontawesome',
          color: '#ff8fb5',
        },
        {
          id: 'github',
          label: 'GitHub',
          href: 'https://github.com/yourname',
          icon: 'github',
          iconProvider: 'fontawesome',
          color: '#d9dcff',
        },
        {
          id: 'qq-group',
          label: 'QQ群',
          href: 'https://qm.qq.com/',
          icon: 'qq',
          iconProvider: 'fontawesome',
          color: '#8fd8ff',
        },
      ],
    },
  ],
  redirects: [
    {
      id: 'example',
      path: '/go',
      to: 'https://example.com/',
      label: '示例外部链接',
      delaySeconds: 10,
      enabled: true,
    },
  ],
  profile: {
    enabled: true,
    name: '你的名字',
    handle: '@yourname',
    avatar,
    avatarAlt: '你的头像',
    greeting: '你好，欢迎来到我的主页',
    tagline: '开发者 · 创作者',
    description: '在这里写一段简短的个人介绍。',
    location: '中国',
    quotes: ['在这里写一句喜欢的话。', '也可以继续添加更多轮换签名。'],
    quoteInterval: 6500,
    typingEffect: true,
    socials: [
      {
        id: 'github',
        label: 'GitHub',
        href: 'https://github.com/yourname',
        icon: 'github',
        iconProvider: 'fontawesome',
        color: '#7d89bd',
        enabled: true,
      },
      {
        id: 'email',
        label: '邮箱',
        href: 'mailto:hello@example.com',
        icon: 'mail',
        color: '#ff9eb9',
        enabled: true,
      },
    ],
  },
  sections: {
    quickLinks: {
      enabled: true,
      title: '探索我的小世界',
      items: [
        {
          id: 'articles',
          title: '文章',
          description: '记录与思考',
          href: '/articles',
          icon: 'book-open',
          enabled: true,
        },
      ],
    },
    navigation: {
      enabled: true,
      title: '我的站点与常用入口',
      items: [
        {
          id: 'docs',
          title: '个人文档',
          description: '公开的技术文档与使用指南',
          href: 'https://docs.example.com/',
          icon: 'book-open',
          accent: '#a9b8ff',
          enabled: true,
        },
      ],
    },
    about: {
      enabled: true,
      title: '关于我',
      description: '在这里填写更详细的介绍。',
      facts: [{ label: '位置', value: '中国', icon: 'map-pin' }],
    },
    contributions: {
      enabled: true,
      title: 'GitHub 提交足迹',
      username: 'yourname',
      apiUrl: 'https://github-contributions-api.jogruber.de/v4/{username}?y=last',
      profileUrl: 'https://github.com/yourname',
      description: '公开贡献记录。',
    },
    projects: { enabled: true, title: 'Project / 项目', items: [] },
    skills: { enabled: true, title: 'Skills / 技能', items: [] },
    articles: {
      enabled: true,
      title: 'Notes / 最近文章',
      limit: 3,
      toc: {
        enabled: true,
        title: '本页导航',
        minLevel: 1,
        maxLevel: 2,
      },
      covers: [
        { slug: 'building-a-calm-homepage', image: friendsBackground, position: 'center 42%' },
        { slug: 'vue-content-structure', image: articleSky, position: 'center' },
        { slug: 'small-open-source-habits', image: homeBackground, position: 'center 35%' },
      ],
    },
  },
  friendsPage: {
    enabled: true,
    autoFavicon: true,
    faviconService: '',
    title: '友链花园',
    subtitle: 'Friends across the stars',
    description: '每一条链接，都是通往另一个小世界的门。',
    applicationText: '在这里填写友链申请方式。',
    applicationEmail: 'hello@example.com',
    items: [],
  },
  footer: {
    enabled: true,
    text: '© 2026 你的名字',
    imageDisclaimer: '本站部分图片资源仅用于非商业展示，版权归原作者所有。如有侵权，请联系删除。',
  },
}
